module Codegen where

import Structures

addSemicolon :: String -> String
addSemicolon x = x ++ ";"

jo :: [String] -> String
jo xs = concat xs

boilerplate :: String -> String
boilerplate = jo ["#include <stdio.h>", newline, "//This code was generated by the noble Gigi Compiler.", newline]

codegenFunction :: String -> Statement -> Statement -> String
codegenFunction x1 x2 x3 = jo [((extractTypeAddSpace x2) !! 0), x1, "() {\n", (codegenStatement x3), "\n}"]

codegenStatement :: Statement -> String
codegenStatement (Add x1 x2) = jo [(codegenStatement x1), " + ", (codegenStatement x2)]
codegenStatement (Subtract x1 x2) = jo [(codegenStatement x1), " - ", (codegenStatement x2)]
codegenStatement (Multiply x1 x2) = jo [(codegenStatement x1), " * ", (codegenStatement x2)]
codegenStatement (Divide x1 x2) =  jo [(codegenStatement x1), " / ", (codegenStatement x2)]
codegenStatement (Power x1 x2) = jo [(codegenStatement x1) ++ " ^ " ++ (codegenStatement x2)]
codegenStatement (Assignment x1 x2 x3) = jo [((extractTypeAddSpace x2) !! 0), x1, " = ", (codegenStatement x3)]
codegenStatement (Defun x1 x2 x3) = codegenFunction x1 x2 x3
codegenStatement (Application x1) = jo [codegenStatement x1, "()"]

codegenStatement (Literal x1) = x1 
codegenStatement _ = ""

codegenStatementAddSemicolon :: Statement -> String
codegenStatementAddSemicolon = addSemicolon . codegenStatement
